###
GET http://localhost:8090/api/client/posts?page=0&size=10

###
GET http://localhost:8090/api/client/posts/100

###
POST http://localhost:8090/api/client/posts
Content-Type: application/json

{
  "userId": 557,
  "title": "RESTclient post",
  "body": "My first RESTclient post"
}

###
GET http://localhost:8090/api/client/posts/101

###
PUT http://localhost:8090/api/client/posts
Content-Type: application/json

{
  "id": 100,
  "userId": 10,
  "title": "Updating post record using REST client",
  "body": "Updated post record using REST client"
}

###
DELETE http://localhost:8090/api/client/posts/100