###
GET http://localhost:8090/

### public URL
GET http://localhost:8090/contact

### public URL
GET http://localhost:8090/notice

###
GET http://localhost:8090/myAccount

###
GET http://localhost:8090/myBalance

###
GET http://localhost:8090/myCard

###
GET http://localhost:8090/myLoan

###
# @no-redirect
POST http://localhost:8090/login?username=john.connor%40zuniversity.edu&password=katherineBrewster

###
GET http://localhost:8090/api/students?page=0&size=10

###
GET http://localhost:8090/api/students/searchOlderThan/60

###
POST http://localhost:8090/api/students
Content-Type: application/json

{
    "firstName": "Tom",
    "lastName": "Voldemort",
    "email": "Tom.Voldemort@zuniversity.edu",
    "age": 57
  }

###
GET http://localhost:8090/api/students/21

###
PUT http://localhost:8090/api/students
Content-Type: application/json

{
  "id": 21,
  "firstName": "tom",
  "lastName": "zoldemort",
  "email": "tom.zoldemort@zuniversity.edu",
  "age": 61
}

###
GET http://localhost:8090/api/students/searchByEmail/tom.zoldemort@zuniversity.edu

###
DELETE http://localhost:8090/api/students/21

###
POST http://localhost:8090/login?username=kyle.reez%40zuniversity.edu&password=sarahConnor