###
GET http://localhost:8080/students

###
POST http://localhost:8080/students
Content-Type: application/json

{
    "firstName": "Tom",
    "lastName": "Voldemort",
    "email": "Tom.Voldemort@zuniversity.edu",
    "age": 57
  }

###
GET http://localhost:8080/students/21

###
PUT http://localhost:8080/students
Content-Type: application/json

{
  "id": 21,
  "firstName": "tom",
  "lastName": "zoldemort",
  "email": "tom.zoldemort@zuniversity.edu",
  "age": 60
}

###
DELETE http://localhost:8080/students/21