###
GET http://localhost:8080/

###
GET http://localhost:8080/contact

###
GET http://localhost:8080/notice

###
GET http://localhost:8080/myAccount

###
GET http://localhost:8080/myBalance

###
GET http://localhost:8080/myCard

###
GET http://localhost:8080/myLoan

###
GET http://localhost:8080/students?page=0&size=10

###
GET http://localhost:8080/students/searchOlderThan/60

###
POST http://localhost:8080/students
Content-Type: application/json

{
    "firstName": "Tom",
    "lastName": "Voldemort",
    "email": "Tom.Voldemort@zuniversity.edu",
    "age": 57
  }

###
GET http://localhost:8080/students/21

###
PUT http://localhost:8080/students
Content-Type: application/json

{
  "id": 21,
  "firstName": "tom",
  "lastName": "zoldemort",
  "email": "tom.zoldemort@zuniversity.edu",
  "age": 60
}

###
GET http://localhost:8080/students/searchByEmail/tom.zoldemort@zuniversity.edu

###
DELETE http://localhost:8080/students/21